# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-12 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedades',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SintomaEnfermedad',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SisExperto.Enfermedades')),
            ],
        ),
        migrations.CreateModel(
            name='Sintomas',
            fields=[
                ('descripcion', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='sintomaenfermedad',
            name='sintoma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SisExperto.Sintomas'),
        ),
    ]
