# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-12 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SisExperto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enfermedades',
            new_name='Enfermedad',
        ),
        migrations.RenameModel(
            old_name='Sintomas',
            new_name='Sintoma',
        ),
    ]
