# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-12 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SisExperto', '0002_auto_20161112_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sintomaenfermedad',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
