# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SisExperto', '0003_auto_20161112_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfermedad',
            name='tratamiento',
            field=models.CharField(default='Consulta un medico', max_length=200),
        ),
    ]
